### ISSUE TITLE
odata-mock: update to loopback 4

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#132]
Investigate on the differences coming with loopback 4. If it is still fitting our goals, update to the latest version.
Please check also if a configuration of the models is possible by edmx spec out of the box (currently we are doing a custom transformation)

**Comment by obadrawi** [comment]
To update to loopback4 we have the following issues:
1- we need to change the codebase for the odata mock because loopback4 is completely different than the previous versions
2- we can't use the n-odata-server because it's using loopback2 (we need to figure out a new library to use)

That's why we decided not to upgrade for now
