### ISSUE TITLE
example-combined-odata-mock: fail to register odata api

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/varkes#94]
The combined-odata-mock fails to register odata API when connecting to a kyma cluster with auto-register switched on.

**Comment by obadrawi** [comment]
Fixed the issue in pull request #98

**Comment by obadrawi** [comment]
Problem: The main issue was because the apis for the create service were not exposes in the api.js module and we couldn't just expose the function because of it's request arguments
Solution: creating a seperate function with a callback method that is exposed and is called by the auto register function and the normal create service function
